config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  get 'persons/profile'
  root to: 'posts#index'
  get 'persons/profile', as: 'user_root'

  get 'posts/new'
  get 'posts/create'
  get 'posts/update'
  get 'posts/edit'
  get 'posts/destroy'
  get 'posts/show'
  get 'posts', to: 'posts#index'

  post 'file/create'
  get 'file/show'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)
    case user.role
    when 'admin'
      can :manage, :all
    when 'user'
      can :manage, Post, user_id: user.id
      can :read, :all
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  enumerize :role, in: %i[guest user admin], default: :guest

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :timeoutable,
         :validatable,
         :confirmable

  before_save :change_role

  def change_role
    self.role = :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_controller.rb
require 'fileutils'

class FileController < ApplicationController
  skip_before_action :verify_authenticity_token

  STORAGE = Rails.root.join('tmp/storage')

  def create
    FileUtils.mkdir_p(STORAGE)
    file_name = File.join(STORAGE, params[:userfile].original_filename)
    FileUtils.mv(params[:userfile].tempfile.path, file_name)
  end

  def destroy
  end

  def show
    file_name = File.join(STORAGE, params[:name])
    content = File.open(file_name, 'r', &:read)
    send_data content, type: 'image/jpeg', disposition: 'inline'
  end

  def index
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  PERMITTED_PARAMS = %i[body].freeze

  load_and_authorize_resource

  # Just views
  def new; end
  def edit; end
  def show; end

  def create
    if @post.save
      redirect_to @post
    else
      flash.alert = "Can't save!"
    end
  end

  def update
    if @post.update(create_params)
      redirect_to @post
    else
      flash.alert = "Can't Update!"
    end
  end

  def destroy
    @post.delete
    redirect_to root_url, notice: 'Post deleted'
  end

  def index
    @posts = Post.all
  end

  private

  def create_params
    params.require(controller_name.classify.downcase.to_sym).permit(self.class::PERMITTED_PARAMS)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    Markdown.new(text, %i[hard_wrap autolink no_intra_emphasis]).to_html.html_safe
  end

  def markdown_without_link(text)
    html = markdown(text)
    doc = Nokogiri::HTML.fragment(html)
    doc.search('//a').remove
    doc.xpath("*").first(2).map(&:to_html).join.html_safe
  end

  def markdown_find_images(text)
    (text.scan(/data:[^"]+/) + text.scan(/(http[^"]+(png|jpg|"))/).flatten.map { |i| i.gsub('"', '') }).flatten
  end

  def current_theme
    current_user.theme || 'black'
  end
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.slim
.site-footer
  footer.text-center.text-lg-start.site-panel-color
    .text-center.p-3
      | Educational project:
      a.text-dark href="https://github.com/MikhailVerbitski"  Mikhail Verbitsky

app/views/layouts/_navbar.html.slim
<link rel="stylesheet" href="/assets/navbar.scss"> 

nav.navbar.navbar-expand-lg.navbar-light.site-panel-color
  a.navbar-brand href="/"  Super site
  button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item.active
        a.nav-link href="/posts/new"
          | Create new Post!
          span.sr-only (current)
      li.nav-item
        label#switch.switch
          input#slider onchange="toggleTheme()" type="checkbox" /
          span.slider.round
    .nav-item.dropdown
      - if user_signed_in?
        a.nav-item.nav-link.dropdown-toggle.user-action data-toggle="dropdown" href="#" 
          img.avatar alt="Avatar" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png"
          - current_user.email
        ul.navbar-nav.mr-auto
          .dropdown-menu.dropdown-menu-right
            li.dropdown-item
              = link_to 'Profile', persons_profile_path, :class => 'navbar-link'
            li.dropdown-item
              = link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'
      - else
        ul.navbar-nav.mr-auto
          a.nav-item.nav-link.dropdown-toggle.user-action data-toggle="dropdown" href="#" 
            img.avatar alt="Avatar" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png"
          .dropdown-menu.dropdown-menu-right
            li.dropdown-item
              = link_to 'Sign in', new_user_session_path, :class => 'navbar-link'
            li.dropdown-item
              = link_to 'Registration', new_user_registration_path, :class => 'navbar-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Ads
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" 
    script data-require="marked@*" data-semver="0.3.1" src="http://cdnjs.cloudflare.com/ajax/libs/marked/0.3.1/marked.js" 
    script src="https://cdn.rawgit.com/toopay/bootstrap-markdown/master/js/bootstrap-markdown.js" 
    script src="https://rawgit.com/lodev09/jquery-filedrop/master/jquery.filedrop.js" 
    script src="https://rawgit.com/jeresig/jquery.hotkeys/master/jquery.hotkeys.js" 
  body
    .main-content.main-color
      = render 'layouts/navbar'
      br/
      .alert.alert-success role="alert"
        = notice
      .alert.alert-danger role="alert"
        = alert
      .dynamic-content
        = yield
    = render 'layouts/footer'

app/views/persons/profile.html.slim
link href="/assets/persons.scss" rel="stylesheet" /

.container.bg-white.mt-5.mb-5
  .row.second-color.rounded.shadow
    .col-md-3.border-right
      .d-flex.flex-column.align-items-center.text-center.p-3.py-5
        img.rounded-circle.mt-5 src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQF2psCzfbB611rnUhxgMi-lc2oB78ykqDGYb4v83xQ1pAbhPiB&usqp=CAU" /
        span.font-weight-bold Amelly
        span.text-black-50 amelly12@bbb.com
        span
    .col-md-5.border-right
      .p-3.py-5
        .d-flex.justify-content-between.align-items-center.mb-3
          h4.text-right Profile Settings
        .row.mt-2
          .col-md-6
            label.labels Name
            input.form-control placeholder=("first name") type="text" value="" /
          .col-md-6
            label.labels Surname
            input.form-control placeholder="surname" type="text" value="" /
        .row.mt-3
          .col-md-12
            label.labels PhoneNumber
            input.form-control placeholder=("enter phone number") type="text" value="" /
          .col-md-12
            label.labels Address
            input.form-control placeholder=("enter address") type="text" value="" /
          .col-md-12
            label.labels Email ID
            input.form-control placeholder=("enter email id") type="text" value="" /
          .col-md-12
            label.labels Education
            input.form-control placeholder="education" type="text" value="" /
        .row.mt-3
          .col-md-6
            label.labels Country
            input.form-control placeholder="country" type="text" value="" /
          .col-md-6
            label.labels State/Region
            input.form-control placeholder="state" type="text" value="" /
        .mt-5.text-center
          button.btn.btn-primary.profile-button type="button"  Save Profile
    .col-md-4
      .p-3.py-5
        .d-flex.justify-content-between.align-items-center.experience
          span Edit Experience
          span.border.px-3.p-1.add-experience
            i.fa.fa-plus
            | \&nbsp;Experience
        br/
        .col-md-12
          label.labels Experience in Designing
          input.form-control placeholder="experience" type="text" value="" /
        br/
        .col-md-12
          label.labels Additional Details
          input.form-control placeholder=("additional details") type="text" value="" /

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/edit.html.slim
link href="/assets/posts.scss" rel="stylesheet" /

.container
  .col-12.rounded.shadow.second-color
    = form_with model: @post, class: "", local: true do |f|
      .row.justify-content-md-center
        .col-md-12
          h1 Editor
          br/
          textarea#post_body name="post[body]" placeholder=("Say something...")
            = @post.body
          br/
          #post_body-preview-container.border.rounded
            #post_body-preview.well.well-sm.well-light.md-preview.margin-top-10
      br/
      #saveButton.text-right
        button.btn.btn-primary name="button" type="submit"  Update

app/views/posts/index.html.slim
link href="/assets/posts.scss" rel="stylesheet" /

.wrapper
  - @posts.each do |post|
    .shadow.card-overlay.rounded
      = image_tag markdown_find_images(post.body).first
      = link_to post_path(post)
        span.overlay-text
          = markdown_without_link(post.body)

app/views/posts/new.html.slim
link href="/assets/posts.scss" rel="stylesheet" /

.container
  .col-12.rounded.shadow.second-color
    = form_with model: @post, class: "", local: true do |f|
      .row.justify-content-md-center
        .col-md-12
          h1 Editor
          br/
          textarea#post_body name="post[body]" placeholder=("Say something...")
          br/
          #post_body-preview-container.border.rounded
            #post_body-preview.well.well-sm.well-light.md-preview.margin-top-10
      br/
      #saveButton.text-right.buttons-wrapper
        button.btn.btn-primary name="button" type="submit" style="grid-column-start: 10;"  Save

app/views/posts/show.html.slim
link href="/assets/posts.scss" rel="stylesheet" /

.container
  .col-12.second-color.rounded.shadow
    = markdown(@post.body)
  - if can?(:destroy, @post) && can?(:update, @post)
    .col-12.buttons-wrapper.second-color.rounded.shadow
      = can?(:destroy, @post) ? link_to("Delete", post_path(@post), class: "btn btn-primary", method: :delete, style: "grid-column-start: 9;") : ''
      = can?(:update, @post)  ? link_to('Update', edit_post_path(@post), class: 'btn btn-primary', style: "grid-column-start: 10;") : ''